batch_size: 1
width: 256
height: 256
scale: 1
down_N: 2
data:
  eval:
    NEU:
      mask_loader: true
      gt_path: /root/data/gd/CDM/data/NEU-Seg/examplesmask
      mask_path: /root/data/gd/CDM/data/NEU-Seg/examplesmask
      image_size: 256
      class_cond: false
      deterministic: true
      random_crop: false
      random_flip: false
      return_dict: true
      drop_last: false
      batch_size: 1
      return_dataloader: true
      